spring:
  # DB Setting
  datasource:
    url: jdbc:mysql://database-bookmind.c9i0ceu2mgty.ap-northeast-2.rds.amazonaws.com:3306/bookmind
    username: shLim
    password: graD789#!
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA, Hibernate Setting
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
# Logging Setting
logging:
  level:
    root: info
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace


