spring:
  # DB Setting
  datasource:
    url: jdbc:h2:tcp://localhost/~/graduation
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # JPA, Hibernate Setting
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
# Logging Setting
logging:
  level:
    root: info
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace


